# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.
#
# When running your server locally, the server ports are the same as the public
# facing ports.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: https

# Database - dummy local PostgreSQL (not used, all data via Supabase REST API)
# This is only here to satisfy Serverpod's startup requirements
database:
  host: localhost
  port: 5432
  name: postgres
  user: postgres
  requireSsl: false
  isUnixSocket: false

# This is the setup for Redis.
# Disabled for local development - enable when Redis is available
redis:
  enabled: false
  host: localhost
  port: 6379
  requireSsl: false

maxRequestSize: 524288 # The maximum size of requests allowed in bytes

sessionLogs:
  persistentEnabled: false
  consoleEnabled: true
  # consoleLogFormat: text # Defaults to "json", options are "text" or "json"

futureCallExecutionEnabled: true # Enable future calls for action log sync

#futureCall:
#  concurrencyLimit: 1 # Defaults to 1, a negative or null value removes the limit
#  scanInterval: 5000 # Unit in milliseconds, defaults to 5000

# Security secret — loaded from environment variable
serviceSecret: ${SERVICE_SECRET}
